export const TECH_ICONS: Record<string, string> = {
  "React": "logos:react",
  "Vue": "logos:vue",
  "Angular": "logos:angular-icon",
  "Next.js": "logos:nextjs-icon",
  "Vite": "logos:vitejs",
  "TypeScript": "logos:typescript-icon",
  "Tailwind CSS": "logos:tailwindcss-icon",
  "Node.js": "logos:nodejs-icon",
  "NestJS": "logos:nestjs",
  "Golang": "selfhst:golang",
  "Python": "logos:python",
  "PostgreSQL": "logos:postgresql",
  "MySQL": "logos:mysql",
  "MongoDB": "devicon:mongodb",
  "Firestore": "vscode-icons:file-type-firestore",
  "Redis": "logos:redis",
  "Firebase": "logos:firebase",
  "AWS": "logos:aws",
  "GCP": "logos:google-cloud",
  "Docker": "logos:docker-icon",
  "CI/CD": "logos:github-actions",
  "Vercel": "logos:vercel-icon",
  "Flutter": "logos:flutter",
  "React Native": "logos:react",
  "Payment Gateway": "logos:stripe",
  "GraphQL": "logos:graphql",
  "REST API": "logos:postman-icon",
  "Laravel": "devicon:laravel",
  "Google Cloud": "devicon:googlecloud",
  "Express": "bxl:express-js",
  "Rest API": "dashicons:rest-api",
  "Payment Integration": "ri:secure-payment-fill",
  "Cloud Storage": "typcn:cloud-storage",
  "OAuth Providers": "mdi:two-factor-authentication",
  "Javascript": "devicon:javascript",
  "Typescript": "devicon:typescript",
  "Next": "bxl:next-js",
  "Tailwind": "devicon:tailwindcss",
  "Mysql": "devicon:mysql",
  "Node JS": "logos:nodejs",
  "Filament": "devicon:filamentphp",
  "Bloc": "file-icons:bloc",
  "Prisma": "devicon:prisma",
  "Redux": "devicon:redux",
  "Cloudflare R2": "devicon:cloudflare",
  "Supabase": "devicon:supabase",
  "Astro": "devicon:astro",
  "Fast API": "devicon:fastapi",
  "RabbitMQ": "devicon:rabbitmq",
  "Nuxt": "devicon:nuxt"
};
